### ISSUE TITLE
Use TeakHostname for logging, heartbeat, rewards, and notification receipts

### ISSUE THREAD

**Issue by AlexSc** [GoCarrot/teak-ios#68]
TeakHostname is currently used for primary API calls. It should be extended to also be used for SDK logging, rewards requests, heartbeat, and notification receipts. This will allow builds to direct all traffic to a completely independent Teak deployment.

**Comment by ZeroStride** [comment]
The notification extensions can't access memory inside the host app, which is where the value for the `TeakHostname` is located.

How totally-correct should this be solved?

**Comment by AlexSc** [comment]
I'm not sure what you're asking with that.

It should be possible to change the hostname that is used for all communication. Ideally it can be updated in once place, but if not, fine. But it's not acceptable for some things to use one hostname and other things to use a different hostname.

**Comment by ZeroStride** [comment]
Updated at build time, or at run time?

It can be a #define, that's easy.

**Comment by AlexSc** [comment]
Build time is fine
